version: '3.7'

networks:
  mtproxy:
    driver: bridge
    name: mtproxy
    attachable: true

services:
  mtproxy:
    image: telegrammessenger/proxy:1.4
    container_name: mtproxy
    hostname: mtproxy
    ulimits:
        nofile:
          soft: 98304
          hard: 98304
    networks:
      - mtproxy
    ports:
      - 443:443
    volumes:
      - "./proxy-config:/data"
    environment:
#      - SECRET_COUNT=16 # for generate
### after generate
      - SECRET=a5300dda6ca704e8d19eeeeb82a85ee2
    restart: always
    logging:
      driver: json-file
      options:
        max-size: 100m
        max-file: '2'
